#define LINUX 
#define PVR_BUILD_DIR "mt6577"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 531
#define SGX531 
#define SUPPORT_SGX531 
#define SUPPORT_SGX 
#define SGX_CORE_REV 110
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define DISPLAY_CONTROLLER mtklfb
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 0
#define RELEASE 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SGX_FEATURE_SYSTEM_CACHE 
#define PVRSRV_USSE_EDM_STATUS_DEBUG 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEW_PVR_DPF 
#define PVRSRV_NEED_PVR_DPF 
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SGX_DYNAMIC_TIMING_INFO 
#define SYS_SGX_ACTIVE_POWER_LATENCY_MS 100
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define PVRSRV_DUMP_MK_TRACE 
#define ANDROID 
#define PVR_NO_FULL_CACHE_OPS 
#define USE_ARGB8888_FB 
#define MTK_USE_GDC 
#define MTK_DEBUG_LFB 
#define MTK_DEBUG_TIMER_MONITOR 
#define MTK_CLK_CTRL 
