#
# Makefile for nfc devices
#
#ifdef CONFIG_MTK_NFC
obj-$(CONFIG_MTK_NFC_INSIDE)   += microread.o
microread-objs  := open_nfc_main.o
microread-objs  += open_nfc_custom.o

obj-$(CONFIG_MTK_NFC_NXP)   += pn544.o
#endif

#obj-y		+= pn544.o
#obj-y       += microread.o
