/***
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK-DISTRIBUTED SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK-DISTRIBUTED SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK-DISTRIBUTED
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK-DISTRIBUTED SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM.
 */

#ifndef _MTK_CPU_MANAGEMENT
#define _MTK_CPU_MANAGEMENT

#define DVFS_OPP1 (1)
#define DVFS_OPP2 (2)
#define DVFS_OPP3 (3)
#define DVFS_OPP4 (4)
#define DVFS_OPP5 (5)
#define DVFS_OPP6 (6)
/*
typedef enum {
	EVENT_THERMAL	= 0,
	EVENT_VIDEO,
	EVENT_SCREEN_ON_OFF,
	EVENT_COUNT
} mtk_cpu_management_event;
*/

struct module_info {
	char module_name[12];
	int mask[10];
	struct list_head link;
};

extern int cpu_opp_mask(char *name, int *mask, bool flag);
//extern int cpu_opp_limit(mtk_cpu_management_event event, int limited_freq, int limited_cpu, bool flag);


#endif //enf of #ifndef _MTK_CPU_MANAGEMENT