obj-$(CONFIG_MTK_USBFSH) := musbfsh_core.o musbfsh_host.o musbfsh_hsdma.o musbfsh_mt65xx.o musbfsh_virthub.o
#obj-m := usb11.o
#usb11-objs := musbfsh_core.o musbfsh_host.o musbfsh_hsdma.o musbfsh_mt65xx.o musbfsh_virthub.o

ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/power/ -I$(srctree)/drivers/usb/core
